# Generated by Django 6.1.1 on 2026-09-29 16:03

import django.db.models.deletion
import fairpanel_core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_event_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('submissions_open', models.DateTimeField(blank=True, null=True)),
                ('submissions_close', models.DateTimeField(blank=True, null=True)),
                ('judging_open', models.DateTimeField(blank=True, null=True)),
                ('judging_close', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('judging', 'Judging'), ('published', 'Results Published'), ('archived', 'Archived')], default='active', max_length=32)),
                ('team_capacity', models.PositiveIntegerField(default=4)),
                ('min_reviews_per_project', models.PositiveIntegerField(default=3)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fairpanel_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_question_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Single Select'), ('checkbox', 'Checkbox')], default='text', max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_custom_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_prize_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_prizes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_rubric_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_rubrics',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_criterion_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_score', models.FloatField(default=1.0)),
                ('max_score', models.FloatField(default=5.0)),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.rubric')),
            ],
            options={
                'db_table': 'fairpanel_criteria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_track_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_tracks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_membership_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('judge', 'Judge'), ('participant', 'Participant')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fairpanel_event_memberships',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
