# Generated by Django 6.1.1 on 2026-09-29 16:03

import django.db.models.deletion
import fairpanel_core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_project_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video_url', models.CharField(blank=True, max_length=1000)),
                ('repo_url', models.CharField(blank=True, max_length=1000)),
                ('live_url', models.CharField(blank=True, max_length=1000)),
                ('tech_tags', models.JSONField(blank=True, default=list)),
                ('custom_answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=32)),
                ('eligibility', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible')], default='eligible', max_length=32)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='events.track')),
            ],
            options={
                'db_table': 'fairpanel_projects',
                'ordering': ['-submitted_at', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_media_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fairpanel_project_media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
