# Generated by Django 6.1.1 on 2026-09-29 16:03

import django.db.models.deletion
import fairpanel_core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_assignment_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('conflict', 'Conflict Reported'), ('completed', 'Completed')], default='assigned', max_length=32)),
                ('conflict_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
            ],
            options={
                'db_table': 'fairpanel_assignments',
                'unique_together': {('project', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='JudgeInvite',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_judge_invite_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('raw_token', models.CharField(blank=True, max_length=128)),
                ('invited_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tracks', models.JSONField(blank=True, default=list)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_invites', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_judge_invites',
            },
        ),
        migrations.CreateModel(
            name='ResultSnapshot',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_snapshot_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('ranking_method', models.CharField(choices=[('raw', 'Raw Score'), ('adjusted', 'Adjusted Score (overlap_bias_v1)')], default='raw', max_length=32)),
                ('input_fingerprint', models.CharField(max_length=128)),
                ('warnings_acknowledged', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='events.event')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fairpanel_result_snapshots',
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='ResultRow',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_result_row_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('raw_score', models.FloatField()),
                ('adjusted_score', models.FloatField(blank=True, null=True)),
                ('raw_rank', models.IntegerField()),
                ('adjusted_rank', models.IntegerField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('eligible_review_count', models.IntegerField(default=0)),
                ('normalization_status', models.CharField(default='calibrated', max_length=64)),
                ('warnings', models.JSONField(default=list)),
                ('tied', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_rows', to='projects.project')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='judging.resultsnapshot')),
            ],
            options={
                'db_table': 'fairpanel_result_rows',
                'ordering': ['raw_rank'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrackScope',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_scope_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_track_scopes', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scopes', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(blank=True, related_name='scoped_judges', to='events.track')),
            ],
            options={
                'db_table': 'fairpanel_judge_track_scopes',
                'unique_together': {('judge', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_review_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('rubric_version', models.PositiveIntegerField(default=1)),
                ('criteria_scores', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='judging.assignment')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
            options={
                'db_table': 'fairpanel_reviews',
                'unique_together': {('project', 'judge')},
            },
        ),
    ]
