# Generated by Django 6.1.1 on 2026-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultrow',
            name='project_tagline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resultrow',
            name='project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resultrow',
            name='track_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resultrow',
            name='raw_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultrow',
            name='raw_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
