# Generated by Django 6.1.1 on 2026-09-29 16:03

import django.db.models.deletion
import fairpanel_core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(default=fairpanel_core.utils.gen_audit_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='events.event')),
            ],
            options={
                'db_table': 'fairpanel_audit_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
